### ISSUE TITLE
Not supporting terminal vim

### ISSUE THREAD

**Issue by ShahinSorkh** [doums/darcula#1]
I see you don't support terminal vim.

With a little search, I have found [this SO post][1].
I will try to make it work on terminal vim as well.

Good attempt tho.

[1]: https://stackoverflow.com/q/11765623/3332676

**Comment by doums** [comment]
Hi!

In fact yes it supports vim "terminal". Myself I never use vim gui. But the terminal emulator you use must support true colors -> https://gist.github.com/XVilka/8346728
see `h termguicolors`

For those who do not support it, I have already planned to build the 256-color palette equivalent.

**Comment by ShahinSorkh** [comment]
Oh man, I didn't know about `termguicolors` and the fact that my terminal supports `16m colors`!
Thank you for directing me to it.
Love your work <3
