### ISSUE TITLE
change single colors (or bright-up whole colorscheme)

### ISSUE THREAD

**Issue by jbirnick** [doums/darcula#11]
Hey,
**is there a simple way to change single colors?**

And is there (probably not, but why not ask) a possibility to bright-up the whole colorscheme?

_(Background: I love the Darcula colorscheme, but in my terminal your normal white which is used for most text, is too gray for me. I want to light it up to something like `#dddddd` or `#eeeeee`.)_

**Comment by doums** [comment]
Hi,
> is there a simple way to change single colors?

Have you tried to put something like the following in your `.vimrc` ?
```
let darcula#palette.fg=['#<your_color>', <256_color_code>]
```
If this does not work, so the answer is not. On the other hand you can override a highlight group, see the readme.

> And is there (probably not, but why not ask) a possibility to bright-up the whole colorscheme?

As you thought, no. I remind you that the purpose of this plugin is to reproduce Jetbrains theme as faithfully as possible.
