### ISSUE TITLE
[Question] Is there a way to customize the colour of comments?

### ISSUE THREAD

**Issue by ghost** [doums/darcula#13]
Great work on the plugin. I was just wondering if we could customize the color of the comments (as is possible in IDEA). What about the font color? (Is it possible to have a white font on top of grey background)? (The current font-color scheme is fine for coding, but it seems a bit off while writing articles).

Again, thank you for this awesome plugin.

**Comment by doums** [comment]
Hi,

Thank for the feedback, I appreciate!
In vim the color of things are handled by highlight groups (see `:h highlight`).
A group can contain a name, a foreground and background colors (both for terminal and gui, terminal = ANSI 256 colors, gui = truecolor) and a style.
You can change the colors of a group using the API as described in the README.
For example for comments, you can override the `Comment` group.
If you only want to change the foreground color and the color you want is already in the Darcula's palette put something like this in your `.vimrc`:
```
call darcula#Hi('Comment', darcula#palette.<the_color_you_want>)
```
If the color is not in the palette, write:
```
call darcula#Hi('Comment', ['#EEEEEE', 255])
```
Here 255 is the corresponding 256color of the truecolor `#EEEEEE`. (really useful if your terminal does not support truecolor).
