### ISSUE TITLE
Can'not change :colo back to dracula after changing it to something else

### ISSUE THREAD

**Issue by vatosarmat** [doums/darcula#18]
Hello. Thank you for this plugin! 
But why is this at the beginning of `darcula.vim`?
```vim
if exists("g:darcula")
  finish
endif
let g:darcula = 1
```
If I set darcula in vimrc, then change it to something else, and then wanna change back to darcula, I also have to `:unlet g:darcula`. Is this condition with `finish` really necessary?

**Comment by doums** [comment]
Hi,
These condition seems to be part of best practices when you write a vim plugin. It prevents load the plugin more than once and give to the user the possibility to not load the plugin.
In `:h write-plugin`#NOT LOADING
```
It's possible that a user doesn't always want to load this plugin.  Or the
system administrator has dropped it in the system-wide plugin directory, but a
user has his own plugin he wants to use.  Then the user must have a chance to
disable loading this specific plugin.  This will make it possible: >

  6	if exists("g:loaded_typecorr")
  7	  finish
  8	endif
  9	let g:loaded_typecorr = 1

This also avoids that when the script is loaded twice it would cause error
messages for redefining functions and cause trouble for autocommands that are
added twice.

The name is recommended to start with "loaded_" and then the file name of the
plugin, literally.  The "g:" is prepended just to avoid mistakes when using
the variable in a function (without "g:" it would be a variable local to the
function).

Using "finish" stops Vim from reading the rest of the file, it's much quicker
than using if-endif around the whole file.
```
Based on that, and because switching theme in runtime is quite uncommon, I will not remove this condition.

**Comment by YongJieYongJie** [comment]
@doums Would you be open to reconsidering the decision above to not remove the check?

I took a look at both the built-in plugins and built-in colorschemes, and observe as follows:
 -  only the built-in plugins follow the convention mentioned above, adding a check to avoid re-loading (e.g., https://github.com/neovim/neovim/blob/master/runtime/plugin/gzip.vim), 
 - all built-in colorschemes does not contain the check (e.g. https://github.com/neovim/neovim/blob/master/runtime/colors/blue.vim) can be loaded and reloaded with no issues.

In essence, it would seem that the convention quoted earlier applies to plugins other than colorscheme.
 - This makes sense as a true plugin controls its own unloading, and can unset the variable, whereas a colorscheme does not know that it has been replaced, and cannot unset the variable.
