### ISSUE TITLE
Text in non-current tab not readanle

### ISSUE THREAD

**Issue by andrea-peter** [doums/darcula#2]
When having mutliple tabs, the text on other tabs (all but the one which is displayed) is not readable because the fg and bg colors are very similar.

I'm on xterm in MINGW64

![image](https://user-images.githubusercontent.com/3224512/66475953-ae30bd80-ea94-11e9-93ca-635a89103a47.png)

**Comment by doums** [comment]
Hi!

Yup, that's because I don't have set yet the correct highlight for vanilla tabs and status bar because I use [lightline](https://github.com/itchyny/lightline.vim) for that. But you are right ! I will add this soon !

**Comment by andrea-peter** [comment]
I'll have a look at lightline, thanks
