### ISSUE TITLE
a little "f" in statusline in neovim

### ISSUE THREAD

**Issue by markwu** [doums/darcula#3]
No idea what's going on, but I have a little "f" in statusline under neovim. No problem under vim (macvim).

Macvim version: `VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  8 2019 20:51:53)`
Neovim version: `NVIM v0.5.0-3b3a40978`

* After switch to insert mode and back to normal mode
![螢幕快照 2019-10-10 下午12 49 17](https://user-images.githubusercontent.com/196861/66539910-8a38af00-eb5c-11e9-9d64-c62a7211f92c.png)

* After use fzf plugin
![螢幕快照 2019-10-10 下午12 52 08](https://user-images.githubusercontent.com/196861/66539993-d388fe80-eb5c-11e9-8a0c-453d33558abb.png)

**Comment by doums** [comment]
Hi,

I do not use Neovim and will not add any form of effort / code modification to make it Neovim compliant.

**Comment by markwu** [comment]
https://github.com/doums/darcula/blob/99aeaedce28c34e0c986c063afff1578c9eae641/colors/darcula.vim#L104

I know you don't want to support neovim, but if you change this line to

```vim
    call s:Hi('Cursor', s:cursor, s:fg) 
```

the issue just solved.

For your reference.

**Comment by yanbodiaoweng** [comment]
same issue. 
Thanks @markwu, it works. 
And thank @doums for your wonderful theme

**Comment by doums** [comment]
Ok I admit it .. I was a little angry when I posted previously .. I will add the fix in the code (if it does not break something in vim terminal). And you are welcome @yanbodiaoweng 😉
