### ISSUE TITLE
Theme does not work under tmux with macvim*

### ISSUE THREAD

**Issue by markwu** [doums/darcula#4]
The darcula theme does not work under tmux with vim, but works with neovim.

Left panel is macvim, the version is `VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 8 2019 20:51:53)`
Right panel is neovim, the version is `NVIM v0.5.0-3b3a40978`
macOS version is `10.14.6`
tmux version is `2.9a`
iTerm2 version is `3.36`

![螢幕快照 2019-10-12 下午5 27 50](https://user-images.githubusercontent.com/196861/66699017-c19e8b80-ed15-11e9-97cd-c3ec3e5edbc6.png)

**Comment by doums** [comment]
Macvim is not vim. My plugin is for vim.
